### PR TITLE
Merge commits from AtomLinter/linter-plus

### PR DESCRIPTION
**Pull request by k2b6s9j**
If we are using this repo for a public beta test, we should bring in the latest code from AtomLinter/linter-plus. There might be some remnant legacy code that didn't merge quite right though....

### CODE REVIEW

**Comment by AsaAyers** [comment]
This repo is not useful as a public beta test. If people want to beta test the code they should checkout the repo and run `apm link`.

* This repo doesn't have any of the backward compatibility code, so it only really works with 2 linters.
* all linters depend on you having an app named `linter` installed, so you can't replace `linter` with anything named `linter-plus`

IMO both this repo and apm's [linter-plus](https://atom.io/packages/linter-plus) should be removed before they cause any more confusion to users.

**Comment by k2b6s9j** [comment]
I agree with you that I doesn't make much sense that we have two repos like this, and the test you explain is how I have always done it. But, I only purposed this PR because this is here. I suppose though that is just a good of place as any to talk about taking this repo and the APM package down. In terms of that, I'm alright with taking both down, especially if we are close to releasing the new API.

**Comment by AsaAyers** [comment]
I think the API is pretty stable, but the 250+ commits (github doesn't even tell me the real number) over the last 9 days involved in this PR tells us how stable the main repo isn't. I thought it was going to be ready for release a few days ago, but certainly not with how rapidly things have been changing.

**Comment by k2b6s9j** [comment]
I've been pretty busy the past week, so the little bit that I could keep up with did feel like things were moving pretty rapidly for a "stable" API.

**Comment by k2b6s9j** [comment]
I think we should aim for a release within the next couple of days and make everything else we want/need a minor update.

**Comment by steelbrain** [comment]
I don't think this is required, 'cause we're just gonna remove this one and shift everything over there. Not to mention that it'll break the existing linters depending on this package.

**Comment by steelbrain** [comment]
Closing this PR, as discussed in private.

**Pull request closed without merging**
